AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Drone Inspection Backend

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 128

Resources:

  DroneInspectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DroneInspectionTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  InspectionImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-inspection-images"

  CreateInspectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: createInspection.app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DroneInspectionTable
      Environment:
        Variables:
          TABLE_NAME: !Ref DroneInspectionTable
          BUCKET_NAME: !Ref InspectionImagesBucket
      Events:
        CreateInspection:
          Type: Api
          Properties:
            Path: /inspections
            Method: post

  ListWarehouseInspectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: listWarehouseInspections.app.lambda_handler

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DroneInspectionTable

      Environment:
        Variables:
          TABLE_NAME: !Ref DroneInspectionTable

      Events:
        ListWarehouseInspections:
          Type: Api
          Properties:
            Path: /warehouses/{warehouseId}/inspections
            Method: get

  ListDroneInspectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: listDroneInspections.app.lambda_handler

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DroneInspectionTable

      Environment:
        Variables:
          TABLE_NAME: !Ref DroneInspectionTable

      Events:
        ListDroneInspections:
          Type: Api
          Properties:
            Path: /drones/{droneId}/inspections
            Method: get

  GenerateUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: generateUploadUrl.app.lambda_handler

      Policies:
        - S3CrudPolicy:
            BucketName: !Ref InspectionImagesBucket

      Environment:
        Variables:
          BUCKET_NAME: !Ref InspectionImagesBucket

      Events:
        GenerateUploadUrl:
          Type: Api
          Properties:
            Path: /upload-url
            Method: post

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"